title: K8s - Service Account Token Used Outside Expected Pod
id: b3f95f64-c5c9-4382-999f-dc27b7e69cbd
description: Detects the use of a Kubernetes service account token in an environment not associated with its assigned pod—indicative of token theft or lateral movement.
status: experimental
logsource:
  product: kubernetes
  category: audit
detection:
  selection:
    verb: get
    requestURI|contains: ['/api', '/apis']
    user.username|contains: 'system:serviceaccount:'
    sourceIPs|not_contains: ['pod-assigned-ip-range']
  condition: selection
level: high
tags:
  - attack.privilege_escalation
  - attack.defense_evasion
  - attack.t1557.002
falsepositives:
  - Custom controllers with node-level execution
