title: Cross-Namespace Use of Kube-System ServiceAccount
id: 7c91fe02-d9d0-4bc4-94d9-9e19e40463c6
description: Detects tokens or ServiceAccounts from the `kube-system` namespace being used in another namespace—potential lateral movement or privilege escalation.
status: test
logsource:
  product: kubernetes
  category: application
detection:
  selection:
    sourceNamespace: 'kube-system'
    destinationNamespace|ne: 'kube-system'
  condition: selection
falsepositives:
  - Logging sidecars or DaemonSets (validate tokens)
level: high
tags:
  - attack.lateral_movement
  - attack.persistence
  - platform.kubernetes
